-- Database is an organized collection of structured data.
-- DBMS is a software used for managing database
-- Data definition
-- Data updation
-- data retreival 
-- user administration

-- Query is used to extract data from a database and converts it into a human readable form
-- Every table has a column and every column has a name
-- Column are vertical section of the table
-- Table has a row which is the horizontal information in the table. They are a single information about on single person
-- Field - intersection between a row and a column
-- SELECT * FROM User WHERE id=1